import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap", // Prevents FOIT (Flash of Invisible Text)
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preload"
          href="/svgs/logo-frame-1.svg"
          as="image"
          type="image/svg+xml"
        />
        <link
          rel="preload"
          href="/svgs/logo-frame-2.svg"
          as="image"
          type="image/svg+xml"
        />
        <link
          rel="preload"
          href="/svgs/logo-frame-3.svg"
          as="image"
          type="image/svg+xml"
        />
        <link
          rel="preload"
          href="/svgs/noise.svg"
          as="image"
          type="image/svg+xml"
        />
        <link
          rel="preload"
          href="/svgs/art-1.svg"
          as="image"
          type="image/svg+xml"
        />
        <link
          rel="preload"
          href="/svgs/art-2.svg"
          as="image"
          type="image/svg+xml"
        />
        <link
          rel="preload"
          href="/svgs/art-3.svg"
          as="image"
          type="image/svg+xml"
        />
        <link
          rel="preload"
          href="/svgs/peoplevibe.svg"
          as="image"
          type="image/svg+xml"
        />
        <link
          rel="preload"
          href="/svgs/findamatchtxt.svg"
          as="image"
          type="image/svg+xml"
        />
        <link
          rel="preload"
          href="/svgs/road_path.svg"
          as="image"
          type="image/svg+xml"
        />
        <link
          rel="preload"
          href="/svgs/treehouse.svg"
          as="image"
          type="image/svg+xml"
        />
        <link
          rel="preload"
          href="/svgs/heart_pin.svg"
          as="image"
          type="image/svg+xml"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
